# Compiler and compiler flags
CXX = g++
CXXFLAGS = -std=c++11 -Wall -O2

# Define target executable
TARGET = server

# Source and object files
SRCS = src/backend/main2.cpp src/backend/cpu.cpp # Add other .cpp files here
OBJS = $(SRCS:.cpp=.o)

# Default rule
all: $(TARGET)

# Link object files to create the target executable
$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJS)

# Compile source files into object files
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Clean rule
clean:
	rm -f $(OBJS) $(TARGET)

# Phony targets
.PHONY: all clean
